### ISSUE TITLE
Extend cron job to also check and build torchserve-kfs docker images

### ISSUE THREAD

**Issue by cjidboon94** [fabridamicelli/torchserve-docker#2]
Thank you for doing this! I also use torchserve with kserve and require python>=3.10, making the official torchserve-kfs image a hassle to use (though a lot easier now that I found your images).
Here you can find the Dockerfile:
https://github.com/pytorch/serve/tree/master/kubernetes/kserve
These get built and pushed to: https://hub.docker.com/r/pytorch/torchserve-kfs/tags
Thanks!

**Comment by fabridamicelli** [comment]
Hi @cjidboon94 

thank you for your feedback, happy to hear it's useful for you.
I'll take a look those other builds and see what I can do - thank you for the suggestion!

**Comment by fabridamicelli** [comment]
Hi @cjidboon94 
I just took a look at the Dockerfile and the /kubernetes/kserve/build_image.sh script.
I think I can pull a relatively easy patch to extend the current cron job.
The only problem is that the mentioned [build_image.sh](https://github.com/pytorch/serve/blob/master/kubernetes/kserve/build_image.sh) script has the values of BASE_IMAGE hardcoded and in general does not look in such a great shape like to rely on it at the moment (for example, the script also has harcoded the instruction to push on docker build, which is cumbersome).Plus, the docker github workflows have been broken for a while on the torchserve repo. So it is diffucult to know what their plans are.

Taking all that into account I don't feel confident to put  time and effort on the serve repo to fix from the ground up the build_image.sh script because I don't know in which direction they want to go with that.
Back to your problem, looking at the kserve/Dockerfile, I think I would just use an image from https://hub.docker.com/r/fabridamicelli/torchserve/tags as base image and add the little pieces (like 10 lines of code ) from the /kubernetes/kserve/Dockerfile that I need to run the specific application you're running (by the way, I just tried to run that docker build and also didn't work because of some grpc stuff – once again, I think that part of the project is not yet in great shape).
Something like this:
```Dockerfile
FROM fabridamicelli/torchserve:latest-cpu-python3.11
USER root
RUN pip install --upgrade pip
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh
RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh
COPY kserve_wrapper kserve_wrapper
COPY third_party third_party
COPY ./*.proto ./kserve_wrapper/

RUN python -m grpc_tools.protoc \
    -I third_party/google/rpc \
    --proto_path=./kserve_wrapper \
    --python_out=./kserve_wrapper \
    --grpc_python_out=./kserve_wrapper \
    ./kserve_wrapper/inference.proto \
    ./kserve_wrapper/management.proto

COPY config.properties config.properties

USER model-server

ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh"]

```


Does that make sense?

**Comment by cjidboon94** [comment]
Hi @fabridamicelli ! 
Much appreciated for your swift and detailed answer. I indeed managed to get a solution by replacing the BASE_IMAGE values in the `build_image.sh` script to replace with one of your images which is what your proposed solution also looks like. The issue with the grpc is that you need to initialize the submodule (`git submodule init && git submodule update``) that has the required grpc dep. Then it should be able to build

**Comment by fabridamicelli** [comment]
Hi @cjidboon94 

Ok, I am glad to hear you found a workaround and thank you for the tip.

If it's fine for you I will now close this issue since you have a working solution and for the time being no further work is planned  on this one.
Feel free to open a new issue in the future when the torchserve kserve repo is more stable and I will be happy to extend the workflow if that's what we need.

Best,
F
